HEADERS += \
    $$PWD/egp/64_egp_requestjointeam.hpp \
    $$PWD/egp/65_egp_requestreskin.hpp \
    $$PWD/egp/66_egp_requestrename.hpp \
    $$PWD/egp/67_egp_teamrosterupdate.hpp \
    $$PWD/egp/egp_chat.hpp \
    $$PWD/pkt/000_PKT_Dummy.hpp \
    $$PWD/pkt/001_PKT_C2S_ClientConnect_NamedPipe.hpp \
    $$PWD/pkt/002_PKT_CHAT.hpp \
    $$PWD/pkt/003_PKT_C2S_QueryStatusReq.hpp \
    $$PWD/pkt/004_PKT_S2C_QueryStatusAns.hpp \
    $$PWD/pkt/005_PKT_S2C_StartSpawn.hpp \
    $$PWD/pkt/006_PKT_S2C_CreateHero.hpp \
    $$PWD/pkt/007_PKT_S2C_CreateNeutral.hpp \
    $$PWD/pkt/008_PKT_S2C_CreateTurret.hpp \
    $$PWD/pkt/009_PKT_S2C_PlayAnimation.hpp \
    $$PWD/pkt/010_PKT_C2S_PlayEmote.hpp \
    $$PWD/pkt/011_PKT_S2C_PlayEmote.hpp \
    $$PWD/pkt/012_PKT_S2C_EndSpawn.hpp \
    $$PWD/pkt/013_PKT_S2C_StartGame.hpp \
    $$PWD/pkt/014_PKT_S2C_EndGame.hpp \
    $$PWD/pkt/015_PKT_C2S_CharSelected.hpp \
    $$PWD/pkt/016_PKT_C2S_ClientReady.hpp \
    $$PWD/pkt/017_PKT_C2S_ClientFinished.hpp \
    $$PWD/pkt/018_PKT_NPC_UpgradeSpellReq.hpp \
    $$PWD/pkt/019_PKT_NPC_UpgradeSpellAns.hpp \
    $$PWD/pkt/020_PKT_NPC_IssueOrderReq.hpp \
    $$PWD/pkt/021_PKT_FX_Create_Group.hpp \
    $$PWD/pkt/022_PKT_FX_Kill.hpp \
    $$PWD/pkt/023_PKT_UnitApplyDamage.hpp \
    $$PWD/pkt/024_PKT_Pause.hpp \
    $$PWD/pkt/025_PKT_C2S_MapPing.hpp \
    $$PWD/pkt/026_PKT_S2C_MapPing.hpp \
    $$PWD/pkt/027_PKT_UnitAddGold.hpp \
    $$PWD/pkt/028_PKT_UnitAddEXP.hpp \
    $$PWD/pkt/029_PKT_UserMessagesStart.hpp \
    $$PWD/pkt/030_PKT_NPC_MessageToClient.hpp \
    $$PWD/pkt/031_PKT_AI_Command.hpp \
    $$PWD/pkt/032_PKT_CHAR_SpawnPet.hpp \
    $$PWD/pkt/033_PKT_CHAR_SetCooldown.hpp \
    $$PWD/pkt/034_PKT_NPC_Die.hpp \
    $$PWD/pkt/035_PKT_NPC_ForceDead.hpp \
    $$PWD/pkt/036_PKT_NPC_CastSpellReq.hpp \
    $$PWD/pkt/037_PKT_NPC_CastSpellAns.hpp \
    $$PWD/pkt/038_PKT_NPC_BuffAdd2.hpp \
    $$PWD/pkt/039_PKT_NPC_BuffAddGroup.hpp \
    $$PWD/pkt/040_PKT_NPC_BuffReplace.hpp \
    $$PWD/pkt/041_PKT_NPC_BuffReplaceGroup.hpp \
    $$PWD/pkt/042_PKT_NPC_BuffRemove2.hpp \
    $$PWD/pkt/043_PKT_NPC_BuffRemoveGroup.hpp \
    $$PWD/pkt/044_PKT_NPC_SetAutocast.hpp \
    $$PWD/pkt/045_PKT_SetItem.hpp \
    $$PWD/pkt/046_PKT_BuyItemReq.hpp \
    $$PWD/pkt/047_PKT_BuyItemAns.hpp \
    $$PWD/pkt/048_PKT_RemoveItemReq.hpp \
    $$PWD/pkt/049_PKT_RemoveItemAns.hpp \
    $$PWD/pkt/050_PKT_SwapItemReq.hpp \
    $$PWD/pkt/051_PKT_SwapItemAns.hpp \
    $$PWD/pkt/052_PKT_UseItemAns.hpp \
    $$PWD/pkt/053_PKT_NPC_LevelUp.hpp \
    $$PWD/pkt/054_PKT_NPC_InstantStop_Attack.hpp \
    $$PWD/pkt/055_PKT_Barrack_SpawnUnit.hpp \
    $$PWD/pkt/056_PKT_Turret_Fire.hpp \
    $$PWD/pkt/057_PKT_Turret_CreateTurret.hpp \
    $$PWD/pkt/058_pkt32.hpp \
    $$PWD/pkt/059_PKT_Basic_Attack.hpp \
    $$PWD/pkt/060_PKT_Basic_Attack_Pos.hpp \
    $$PWD/pkt/061_PKT_OnEnterVisiblityClient.hpp \
    $$PWD/pkt/062_PKT_OnLeaveVisiblityClient.hpp \
    $$PWD/pkt/063_PKT_OnEnterLocalVisiblityClient.hpp \
    $$PWD/pkt/064_PKT_OnLeaveLocalVisiblityClient.hpp \
    $$PWD/pkt/065_PKT_World_SendCamera_Server.hpp \
    $$PWD/pkt/066_PKT_World_LockCamera_Server.hpp \
    $$PWD/pkt/067_PKT_SendSelectedObjID.hpp \
    $$PWD/pkt/068_PKT_UnitApplyHeal.hpp \
    $$PWD/pkt/069_PKT_MissileReplication.hpp \
    $$PWD/pkt/070_PKT_ServerTick.hpp \
    $$PWD/pkt/071_PKT_DampenerSwitch.hpp \
    $$PWD/pkt/072_PKT_GlobalCombatMessage.hpp \
    $$PWD/pkt/073_PKT_SynchVersionC2S.hpp \
    $$PWD/pkt/074_PKT_SynchVersionS2C.hpp \
    $$PWD/pkt/075_PKT_AI_TargetS2C.hpp \
    $$PWD/pkt/076_PKT_AI_TargetHeroS2C.hpp \
    $$PWD/pkt/077_PKT_SPM_HierarchicalProfilerUpdate.hpp \
    $$PWD/pkt/078_PKT_SPM_HierarchicalMemoryUpdate.hpp \
    $$PWD/pkt/079_PKT_SPM_HierarchicalBBProfileUpdate.hpp \
    $$PWD/pkt/080_PKT_SPM_SamplingProfilerUpdate.hpp \
    $$PWD/pkt/081_PKT_SPM_AddBBProfileListener.hpp \
    $$PWD/pkt/082_PKT_SPM_RemoveBBProfileListener.hpp \
    $$PWD/pkt/083_PKT_HeroReincarnateAlive.hpp \
    $$PWD/pkt/084_PKT_HeroReincarnate.hpp \
    $$PWD/pkt/085_PKT_Building_Die.hpp \
    $$PWD/pkt/086_PKT_SynchSimTimeS2C.hpp \
    $$PWD/pkt/087_PKT_SynchSimTimeC2S.hpp \
    $$PWD/pkt/088_PKT_SyncSimTimeFinalS2C.hpp \
    $$PWD/pkt/089_PKT_WaypointList.hpp \
    $$PWD/pkt/090_PKT_WaypointListHeroWithSpeed.hpp \
    $$PWD/pkt/091_PKT_ServerGameSettings.hpp \
    $$PWD/pkt/092_PKT_NPC_BuffUpdateCount.hpp \
    $$PWD/pkt/093_PKT_NPC_BuffUpdateCountGroup.hpp \
    $$PWD/pkt/094_PKT_C2S_PlayEmoticon.hpp \
    $$PWD/pkt/095_PKT_S2C_PlayEmoticon.hpp \
    $$PWD/pkt/096_PKT_AvatarInfo_Server.hpp \
    $$PWD/pkt/097_PKT_RemovePerceptionBubble.hpp \
    $$PWD/pkt/098_PKT_AddUnitPerceptionBubble.hpp \
    $$PWD/pkt/099_PKT_AddPosPerceptionBubble.hpp \
    $$PWD/pkt/100_PKT_SpawnMinionS2C.hpp \
    $$PWD/pkt/101_PKT_S2C_StopAnimation.hpp \
    $$PWD/pkt/102_PKT_S2C_ShowHealthBar.hpp \
    $$PWD/pkt/103_PKT_UpdateGoldRedirectTarget.hpp \
    $$PWD/pkt/104_PKT_S2C_ChangeCharacterData.hpp \
    $$PWD/pkt/105_PKT_S2C_PopCharacterData.hpp \
    $$PWD/pkt/106_PKT_S2C_PopAllCharacterData.hpp \
    $$PWD/pkt/107_PKT_S2C_FaceDirection.hpp \
    $$PWD/pkt/108_PKT_S2C_CameraBehavior.hpp \
    $$PWD/pkt/109_PKT_SPM_AddListener.hpp \
    $$PWD/pkt/110_PKT_SPM_RemoveListener.hpp \
    $$PWD/pkt/111_PKT_SPM_AddMemoryListener.hpp \
    $$PWD/pkt/112_PKT_SPM_RemoveMemoryListener.hpp \
    $$PWD/pkt/113_PKT_S2C_DestroyClientMissile.hpp \
    $$PWD/pkt/114_PKT_S2C_ChainMissileSync.hpp \
    $$PWD/pkt/115_PKT_MissileReplication_ChainMissile.hpp \
    $$PWD/pkt/116_PKT_S2C_BotAI.hpp \
    $$PWD/pkt/117_PKT_S2C_AI_TargetSelection.hpp \
    $$PWD/pkt/118_PKT_S2C_AI_State.hpp \
    $$PWD/pkt/119_PKT_OnEvent.hpp \
    $$PWD/pkt/120_PKT_OnDisconnected.hpp \
    $$PWD/pkt/121_PKT_World_SendCamera_Server_Acknologment.hpp \
    $$PWD/pkt/122_PKT_World_SendGameNumber.hpp \
    $$PWD/pkt/123_PKT_NPC_Die_EventHistroy.hpp \
    $$PWD/pkt/124_PKT_C2S_Ping_Load_Info.hpp \
    $$PWD/pkt/125_PKT_S2C_Ping_Load_Info.hpp \
    $$PWD/pkt/126_PKT_C2S_Exit.hpp \
    $$PWD/pkt/127_PKT_S2C_Exit.hpp \
    $$PWD/pkt/128_PKT_C2S_Reconnect.hpp \
    $$PWD/pkt/129_PKT_S2C_Reconnect.hpp \
    $$PWD/pkt/130_PKT_S2C_Reconnect_Done.hpp \
    $$PWD/pkt/131_PKT_Waypoint_Acc.hpp \
    $$PWD/pkt/132_PKT_WaypointGroup.hpp \
    $$PWD/pkt/133_PKT_WaypointGroupWithSpeed.hpp \
    $$PWD/pkt/134_PKT_Connected.hpp \
    $$PWD/pkt/135_PKT_S2C_ToggleInputLockingFlag.hpp \
    $$PWD/pkt/136_PKT_S2C_ToggleFoW.hpp \
    $$PWD/pkt/137_PKT_S2C_ToggleFoWOn.hpp \
    $$PWD/pkt/138_PKT_S2C_SetCircularCameraRestriction.hpp \
    $$PWD/pkt/139_PKT_S2C_LockCamera.hpp \
    $$PWD/pkt/140_PKT_OnReplication.hpp \
    $$PWD/pkt/141_PKT_OnReplication_Acc.hpp \
    $$PWD/pkt/142_PKT_S2C_MoveCameraToPoint.hpp \
    $$PWD/pkt/143_PKT_S2C_PlayTutorialAudioEvent.hpp \
    $$PWD/pkt/144_PKT_ChangeSlotSpellType.hpp \
    $$PWD/pkt/145_PKT_PausePacket.hpp \
    $$PWD/pkt/146_PKT_ResumePacket.hpp \
    $$PWD/pkt/147_PKT_SetFrequency.hpp \
    $$PWD/pkt/148_PKT_SetFadeOut_Push.hpp \
    $$PWD/pkt/149_PKT_SetFadeOut_Pop.hpp \
    $$PWD/pkt/150_PKT_S2C_CreateUnitHighlight.hpp \
    $$PWD/pkt/151_PKT_S2C_RemoveUnitHighlight.hpp \
    $$PWD/pkt/152_PKT_S2C_OpenTutorialPopup.hpp \
    $$PWD/pkt/153_PKT_C2S_OnTutorialPopupClosed.hpp \
    $$PWD/pkt/154_PKT_S2C_OpenAFKWarningMessage.hpp \
    $$PWD/pkt/155_PKT_S2C_CloseShop.hpp \
    $$PWD/pkt/156_PKT_S2C_SetInputLockingFlag.hpp \
    $$PWD/pkt/157_PKT_C2S_OnShopOpened.hpp \
    $$PWD/pkt/158_PKT_S2C_ShowObjectiveText.hpp \
    $$PWD/pkt/159_PKT_S2C_HideObjectiveText.hpp \
    $$PWD/pkt/160_PKT_S2C_RefreshObjectiveText.hpp \
    $$PWD/pkt/161_PKT_S2C_ShowAuxiliaryText.hpp \
    $$PWD/pkt/162_PKT_S2C_HideAuxiliaryText.hpp \
    $$PWD/pkt/163_PKT_S2C_RefreshAuxiliaryText.hpp \
    $$PWD/pkt/164_PKT_S2C_HighlightHUDElement.hpp \
    $$PWD/pkt/165_PKT_S2C_HighlightShopElement.hpp \
    $$PWD/pkt/166_PKT_C2S_TeamSurrenderVote.hpp \
    $$PWD/pkt/167_PKT_S2C_TeamSurrenderVote.hpp \
    $$PWD/pkt/168_PKT_S2C_TeamSurrenderCountDown.hpp \
    $$PWD/pkt/169_PKT_S2C_TeamSurrenderStatus.hpp \
    $$PWD/pkt/170_PKT_S2C_LineMissileHitList.hpp \
    $$PWD/pkt/171_PKT_C2S_TutorialAudioEventFinished.hpp \
    $$PWD/pkt/172_PKT_S2C_HighlightTitanBarElement.hpp \
    $$PWD/pkt/173_PKT_S2C_ToggleUIHighlight.hpp \
    $$PWD/pkt/174_PKT_S2C_DisplayLocalizedTutorialChatText.hpp \
    $$PWD/pkt/175_PKT_S2C_ToolTipVars.hpp \
    $$PWD/pkt/176_PKT_S2C_MuteVolumeCategory.hpp \
    $$PWD/pkt/177_PKT_S2C_OnEventWorld.hpp \
    $$PWD/pkt/178_PKT_S2C_AnimatedBuildingSetCurrentSkin.hpp \
    $$PWD/pkt/179_PKT_S2C_SetGreyscaleEnabledWhenDead.hpp \
    $$PWD/pkt/180_PKT_S2C_DisableHUDForEndOfGame.hpp \
    $$PWD/pkt/181_PKT_ChangeSlotSpellName.hpp \
    $$PWD/pkt/182_PKT_S2C_SwitchNexusesToOnIdleParticles.hpp \
    $$PWD/pkt/183_PKT_S2C_FadeMinions.hpp \
    $$PWD/pkt/184_PKT_S2C_FadeOutMainSFX.hpp \
    $$PWD/pkt/185_PKT_S2C_HeroStats.hpp \
    $$PWD/pkt/186_PKT_S2C_SetAnimStates.hpp \
    $$PWD/pkt/187_PKT_ClientCheatDetectionSignal.hpp \
    $$PWD/pkt/188_PKT_S2C_AddDebugCircle.hpp \
    $$PWD/pkt/189_PKT_S2C_RemoveDebugCircle.hpp \
    $$PWD/pkt/190_PKT_S2C_ModifyDebugCircleRadius.hpp \
    $$PWD/pkt/191_PKT_S2C_ModifyDebugCircleColor.hpp \
    $$PWD/pkt/192_PKT_Undefined.hpp \
    $$PWD/pkt/193_PKT_S2C_Neutral_Camp_Empty.hpp \
    $$PWD/pkt/194_PKT_ResetForSlowLoader.hpp \
    $$PWD/pkt/255_PKT_Batched.hpp \
    $$PWD/shared/connectioninfo.hpp \
    $$PWD/shared/playerliteinfo.hpp \
    $$PWD/base.hpp \
    $$PWD/packetenums.hpp \
    $$PWD/packets.hpp
