#ifndef CHARACTERINTERMEDIATE_H
#define CHARACTERINTERMEDIATE_H

#include "chardata.hpp"

struct CharacterIntermediate
{
    float mFlatCooldownMod = 0;
    float mPercentCooldownMod;
    float mFlatHPPoolMod;
    float mPercentHPPoolMod;
    float mFlatPARPoolMod;
    float mPercentPARPoolMod;
    float mFlatHPRegenMod;
    float mPercentHPRegenMod;
    float mFlatPARRegenMod;
    float mPercentPARRegenMod;
    float mPercentHardnessMod;
    float mFlatMovementSpeedMod;
    float mPercentMovementSpeedMod;
    float mPercentMultiplicativeMovementSpeedMod;
    float mMoveSpeedFloorMod;
    float mFlatArmorMod;
    float mPercentArmorMod;
    float mFlatArmorPenetrationMod;
    float mFlatMagicPenetrationMod;
    float mPercentArmorPenetrationMod;
    float mPercentMagicPenetrationMod;
    float mFlatSpellBlockMod;
    float mPercentSpellBlockMod;
    float mFlatMissChanceMod;
    float mFlatDodgeMod;
    float mFlatCritChanceMod;
    float mFlatCritDamageMod;
    float mPercentCritDamageMod;
    float mFlatPhysicalDamageMod;
    float mPercentPhysicalDamageMod;
    float mFlatMagicDamageMod;
    float mPercentMagicDamageMod;
    float mFlatPhysicalReduction;
    float mPercentPhysicalReduction;
    float mFlatMagicReduction;
    float mPercentMagicReduction;
    float mPercentEXPBonus;
    float mFlatAttackRangeMod;
    float mPercentAttackRangeMod;
    float mFlatCastRangeMod;
    float mPercentCastRangeMod;
    float mAcquisitionRangeMod;
    float mPercentAttackSpeedMod;
    float mPercentMultiplicativeAttackSpeedMod;
    float mPercentHealingAmountMod;
    float mPercentLifeStealMod;
    float mPercentSpellVampMod;
    float mPercentRespawnTimeMod;
    float mPercentGoldLostOnDeathMod;
    float mAttackSpeedMod;
    float mBaseAttackDamage;
    float mBaseAbilityDamage;
    float mCritDamageMultiplier;
    float mScaleSkinCoef;
    float mMissChance;
    float mDodge;
    float mCrit;
    float mArmor;
    float mSpellBlock;
    float mHPRegenRate;
    float mBasePARRegenRate;
    float mPARRegenRate;
    float mMoveSpeed;
    float mAttackRange;
    float mCastRange;
    float mFlatBubbleRadiusMod;
    float mPercentBubbleRadiusMod;
    float m_FlatHPModPerLevel;
    float m_FlatMPModPerLevel;
    float m_FlatArmorModPerLevel;
    float m_FlatSpellBlockModPerLevel;
    float m_FlatHPRegenModPerLevel;
    float m_FlatMPRegenModPerLevel;
    float m_FlatPhysicalDamageModPerLevel;
    float m_FlatMagicDamageModPerLevel;
    float m_FlatMovementSpeedModPerLevel;
    float m_PercentMovementSpeedModPerLevel;
    float m_PercentAttackSpeedModPerLevel;
    float m_FlatCritChanceModPerLevel;
    float m_FlatCritDamageModPerLevel;
    float m_FlatDodgeMod;
    float m_FlatDodgeModPerLevel;
    float m_FlatArmorPenetrationMod;
    float m_FlatArmorPenetrationModPerLevel;
    float m_PercentArmorPenetrationMod;
    float m_PercentArmorPenetrationModPerLevel;
    float m_PercentCooldownMod;
    float m_PercentCooldownModPerLevel;
    float m_FlatTimeDeadMod;
    float m_FlatTimeDeadModPerLevel;
    float m_PercentTimeDeadMod;
    float m_PercentTimeDeadModPerLevel;
    float mFlatGoldPer10Mod;
    float m_FlatMagicPenetrationMod;
    float m_FlatMagicPenetrationModPerLevel;
    float m_PercentMagicPenetrationMod;
    float m_PercentMagicPenetrationModPerLevel;
    float m_NonHealingFlatHPPoolMod;
};


#endif // CHARACTERINTERMEDIATE_H
